export enum HealthStatus{
    HEALTHY = 'HEALTHY',
    MILD_ILLNESS = 'MILD_ILLNESS',
    SEVERE_ILLNESS = 'SEVERE_ILLNESS',
    INJURED = 'INJURED',
    RECOVERING = 'RECOVERING',
    SPECIAL_CARE_NEED = 'SPECIAL_CARE_NEED',
    DECEASED = 'DECEASED',
}